import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

/*
 * Inter variable font with the `opsz` (optical-size) axis enabled —
 * this gives us the "Inter Display" variant at large font-sizes via
 * `font-optical-sizing: auto` (set on body in globals.css). One variable
 * font file covers the full 100..900 weight range, so this is the leanest
 * way to ship Inter Display without duplicating per-weight static files.
 *
 * Cyrillic subset is mandatory (UA-EN bilingual surface — ADR-0003).
 */
const interDisplay = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
  display: "swap",
  axes: ["opsz"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
